config/routes.rb
Rails.application.routes.draw do

  root 'mailinglists#index'

  resources :mailinglists do
    resources :subscribers
  end

end

app/models/concerns/peytzmail/client.rb
module Peytzmail
  module Client
    extend ActiveSupport::Concern

    class Connection < Faraday::Connection
      def initialize(options = {})
        defaults = {url: 'https://test.peytzmail.com/api/v1'}
        super(defaults.merge(options))
        adapter(:net_http)
        response(:logger)
        # So this is an authenticated connection
        basic_auth($peytzmail_key, '')
      end
    end

    included do
      extend(ClassMethods)
    end

    def save
      if id.present?
        put
      else
        run_callbacks :create do
          post
        end
      end
    end

    def post
      self.class
        .post(as_json)
    end

    module ClassMethods
      def url_root(options = {}, method = :get)
        ''
      end

      # This will be user to compose the url. Also, to get
      #  the reponse body data.
      # So for Mailinglist, it will return "mailinglists".
      # You can overwrite this in the model.
      def url_name(method = :get)
        to_s
          .downcase
          .pluralize
      end

      # Combines url_root and url_name
      # For example: /mailinglists/:id/subscribers
      def full_url(options = {}, method = :get)
        url = [url_root(options, method), url_name(method) + '.json']
              .reject(&:blank?)
              .join('/')
        url
      end

      def get_one(id, options = {})

      end

      def instantiate_one(attrs)
        # TODO: We do not declare all fields. So we can't do this:
        #   new(attrs)
        # will raise UknownAttr.. error. will need somethign safer. Also, how the fuck they can trust an unknown API server?
        obj = new
        attrs.each do |k, v|
          obj.public_send("#{k}=", v)
        end rescue nil
        obj
      end

      def get_many(options = {})
        # TODO: Add debugging
        con = Connection.new
        response = con.get(full_url(options))

        data = JSON.load(response.body)

        ary = data[url_name]
        ary.map { |attrs| instantiate_one(attrs) }
      end

      def post(options = {})
        con = Connection.new
        con.post full_url(options, :post), options
      end

      def all(options = {})
        get_many(options)
      end
    end
  end
end

app/models/mailinglist.rb
class Mailinglist
  # requered attributes
  attr_accessor :title, :default_template, :send_confirmation_mail, :send_welcome_mail

  # optional
  attr_accessor :description

  attr_accessor :id

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include Peytzmail::Client

  # FIXME: ActiveModel::Conversion returns the self obj. So...
  def to_param
    id
  end
end

app/models/subscriber.rb
# /api/v1/mailinglists/<mailinglist-id>/subscribers.json
class Subscriber
  attr_accessor :first_name, :last_name, :mailinglist_id

  # required
  attr_accessor :email, :malinglist_ids

  attr_accessor :id

  include ActiveModel::Model
  include ActiveModel::Conversion
  include ActiveModel::Validations
  include Peytzmail::Client

  extend ActiveModel::Callbacks

  define_model_callbacks :create

  before_create :align_mailinglist_ids

  # FIXME:
  def to_param
    id
  end

  # We want to move malinglist_id into malinglist_ids
  def align_mailinglist_ids
    @mailinglist_ids ||= []
    @mailinglist_ids << @mailinglist_id
    @mailinglist_ids.uniq!
  end

  # I could not find an example of subscribing with /subscribers api.
  # It seems /subscribe just adds a new subscriber,
  #  so we use /mailinglists/:id/subscribe
  def subscribe
    run_callbacks :create do
      con = Connection.new
      url = [Mailinglist.url_name, 'subscribe'].join('/') + '.json'
      payload = subscribe_payload

      response = con.post(url, payload)

      Rails.logger.debug response.body
      Rails.logger.debug payload
    end
  end

  def subscribe_payload
    only = %w(email first_name last_name)
    payload = {
      subscribe:
        {
          mailinglist_ids: @mailinglist_ids,
          subscriber: as_json(only: only)
        }
    }
  end

  # def self.url_name(method = :get)
  #   if method == :post
  #     'subscribe' # XXX: ugly.
  #   else
  #     super
  #   end
  # end

  def self.url_root(options = {}, method = :get)
    # If we want filtering by mailinglist_id
    if method == :get && options.key?(:mailinglist_id)
      ['mailinglists', options[:mailinglist_id]]
        .flatten
        .join('/')
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/mailinglists_controller.rb
class MailinglistsController < ApplicationController
  def index
    @mailinglists = Mailinglist.all
  end

  def create
    render text: 'ok'
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def index
    @subscribers = Subscriber.all(mailinglist_options)
  end

  def create
    subscriber = Subscriber.new(subscriber_params)
    subscriber.subscribe
    redirect_to mailinglist_subscribers_path(mailinglist_options)
  end

  def new
    @subscriber = Subscriber.new
  end

  private

  def mailinglist_options
    {mailinglist_id: params[:mailinglist_id]}
  end

  def subscriber_params
    attrs = params
            .require(:subscriber)
            .permit(:email, :first_name, :last_name)
    attrs.merge(mailinglist_options)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mailinglists_helper.rb
module MailinglistsHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SbsSample</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="header">
    <%= link_to "Malinglists", mailinglists_path %> <%# link_to "New subscriber", new_subscriber_path %>
  </div>

  <div id="content">
    <%= yield %>
  </div>

</body>
</html>

app/views/mailinglists/index.html.erb
<h2>Mailinglists</h2>

<% @mailinglists.each do |ml| %>
  <p>
    <%= link_to ml.title, mailinglist_subscribers_path(ml) %>
  </p>
<% end %>

app/views/subscribers/index.html.erb
<h2>Subscribers</h2>

<p><%= link_to "Add new subscriber", new_mailinglist_subscriber_path %>


<h3 style="color: red;">NOTE: Your API doc is not correct. <a href="http://test.peytzmail.com/api/v1/documentation#toc_34">http://test.peytzmail.com/api/v1/documentation#toc_34</a><br />
  You return a list of mailinglist<->subscriber relations instead of subscribers data.</h3>

<% @subscribers.each do |subscriber| %>
  <p>
    id: <%= subscriber.id %> email: <%= subscriber.email %> <%= subscriber.first_name %>
  </p>
<% end %>

app/views/subscribers/new.html.erb
<h2>Add a new Subscriber</h2>

<%= form_for @subscriber, url: mailinglist_subscribers_path, method: :post do |f| %>
  <p>Email: <%= f.text_field :email %></p>
  <p>First name: <%= f.text_field :first_name %></p>
  <p>Last name: <%= f.text_field :last_name %></p>
  <%= f.submit %>
<% end %>